[toolchain]
# Stable
#channel   = "1.73.0" # rustc 1.73.0 (8ca44ef9c 2023-07-10)
# Nightly
channel    = "1.83" # rustc 1.74.0-nightly (8b4b20836 2024-02-08)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile    = "minimal"
targets    = ["x86_64-unknown-linux-musl"]
