[toolchain]
# Stable
#channel   = "1.73.0" # rustc 1.73.0 (8ca44ef9c 2023-07-10)
# Nightly
channel    = "nightly-2023-07-11" # rustc 1.71.0-nightly (8b4b20836 2023-07-11)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src"]
profile    = "minimal"
