name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: 'Run Rust tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: cargo test --release --locked --all
    - name: Build node
      run: cargo build --release --locked

  lint:
    name: 'Run lints'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check Cargo.toml Format
      run: |
        if taplo --version &> /dev/null; then
          echo "taplo-cli is already installed"
        else
          cargo install taplo-cli
        fi
        taplo fmt --check
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --release --all --tests -- -D warnings
